archs:
  - ppc64le:
      distributions:
        - el7
  - s390x:
      distributions:
        - fc29
  - x86_64:
      distributions:
        - el7
        - fc29

release_branches:
  master:
    - ovirt-master
  ovirt-4.3:
    - ovirt-4.3

stages:
  - build-artifacts:
      substages:
        - build-py27
  - check-patch:
      archs:
        - x86_64
      substages:
        - install:
            run-if:
              file-changed:
                - 'vdsm.spec.in'
                - '*Makefile.am'
                - 'automation/*'
                - 'build-aux/*'
        - linters:
            distributions:
              - fc29
        - tests-py27:
            runtime-requirements:
              host-distro: same
        - tests-py37:
            runtime-requirements:
              host-distro: same
            distributions:
              - fc29
  - check-network: &check-network
      archs:
        - x86_64
      substages:
        - functional-linux-bridge:
            runtime-requirements:
              support-nesting-level: 2
              isolation-level: container
            distributions:
              - el7
        - functional-ovs-switch:
            runtime-requirements:
              support-nesting-level: 2
              isolation-level: container
            distributions:
              - el7
        - functional-linux-bridge-lib:
            runtime-requirements:
              support-nesting-level: 2
              isolation-level: container
            distributions:
              - fc29
        - functional-ovs-switch-lib:
            runtime-requirements:
              support-nesting-level: 2
              isolation-level: container
            distributions:
              - fc29
  - poll-upstream-sources:
      <<: *check-network
      script:
        from-file: automation/check-network.{{ substage }}.sh
